### ISSUE TITLE
História 1.2: Como usuário preciso fazer login no aplicativo

### ISSUE THREAD

**Issue by IsabelaPSouza** [dedezinholindo/MC426#12]
Como usuário do sistema (membro da comunidade local, preocupaco com a segurança do bairro) eu preciso conseguir fazer um login no app usando Username ou Email e Senha para que eu possa acessar uma conta uma vez que a mesma foi criada para interagir com os membros da minha comunidade.

Critérios de Aceite:
- Em casos de erro o usuário deve ser notificado
- O login deve funcionar com username ou email
- O backend deve retornar um id de usuário após o login 
- O id deve ser salvo para realizar novas chamadas na api
- O front-end deve ser implementado baseado no figma
- O backend deve estar conectado a um banco de dados para acessar as informações de usuário

Figma: https://www.figma.com/file/DhUKqVbSlzQPt4h17PJVY3/Press2Safe?type=design&node-id=16-396&mode=design&t=WSO5Be5rOcnOAEud-0

Esta história é parte do https://github.com/dedezinholindo/MC426/issues/10

**Comment by IsabelaPSouza** [comment]
MRs para a feature:

backend:

- https://github.com/dedezinholindo/MC426/pull/34
- https://github.com/dedezinholindo/MC426/pull/4

frontend:

- https://github.com/dedezinholindo/MC426/pull/6
- https://github.com/dedezinholindo/MC426/pull/9
- https://github.com/dedezinholindo/MC426/pull/33

**Comment by brenofranca83** [comment]
OS 4 últimos critérios são detalhes de implementação. Lembrem que user stories são do ponto de vista do usuário, que não sabe o que é ID, front-end, back-end... O comportamento observado após o uso da funcionalidade para verificar se a mesma está correta deve sempre partir do que o usuário consegue observar.
