### ISSUE TITLE
História 3.1: Como usuário gostaria de fazer denúncia de crimes com opção de anonimato

### ISSUE THREAD

**Issue by IsabelaPSouza** [dedezinholindo/MC426#19]
Como usuário (membro da comunidade local, que passei por uma situação de perigo e preocupado com a segurança do bairro) devo conseguir criar posts de denúncias de crimes com opção de anonimato. Dessa forma estarei contribuindo para o mapeamento de ocorrências na minha região e alertando outros sobre isso.

Critérios de Aceite:

- Ao selecionar a opção anônima nenhum dado de identificação do usuário deve ser mandado para o backend
- Um usuário pode criar vários posts
- Em caso de erro na criação do post o usuário deve ser avisado
- O front não deve enviar requests caso os campos obrigatórios não estejam preenchidos
- O post deve conter: Texto descritivo, Título, Foto (opcional), Localização , se é anônimo ou não, id de usuário do publicador (se não for anônimo)
- Quantidade de Votes (up ou down) assim que criado precisa ser 0

Figma: to be done

Deve ser implementado um backend conectado a um banco de dados para guardar os posts.
Deve ser implementado um front-end baseado no figma.
Esta história é parte do #18

**Comment by ShiryuReb** [comment]
MRs para a feature:

backend:

- https://github.com/dedezinholindo/MC426/pull/7

frontend:

- https://github.com/dedezinholindo/MC426/pull/32

correções:

- https://github.com/dedezinholindo/MC426/pull/27
- https://github.com/dedezinholindo/MC426/pull/28
- https://github.com/dedezinholindo/MC426/pull/37
- https://github.com/dedezinholindo/MC426/pull/48
- https://github.com/dedezinholindo/MC426/pull/56

Não foi necessário a criação do Figma nessa etapa.
