### ISSUE TITLE
História 3.2: Como usuário gostaria de fazer validação de denúncias usando o sistema de upvote e downvote

### ISSUE THREAD

**Issue by IsabelaPSouza** [dedezinholindo/MC426#20]
Como usuário (membro da comunidade local, preocupado com a segurança do bairro) gostaria de fazer validação de denúncias usando o sistema de upvote e downvote. Dessa forma posso validar se as informações passadas por terceiros estão condizentes com a realidade ou não.

Critérios de Aceite:

- Um usuário deve conseguir votar apenas uma vez em uma post de denúncia
- As informações de voto devem ser salvas no banco apenas com a quantidade de up e down o post teve (limitando 1 por usuário)
- Um usuário pode trocar seu voto 
- O front-end deve ser implementado baseado no figma.
- O backend deve estar conectado a um banco para atualizar os up e down votes
- O usuário publicador (nem nenhum outro) deve ter acesso as informações de quem votou na sua publicação

Figma: to be done

Esta história é parte do #18

**Comment by ShiryuReb** [comment]
MRs para a feature:

backend:

- https://github.com/dedezinholindo/MC426/pull/7

frontend:

- https://github.com/dedezinholindo/MC426/pull/43

correções:

- https://github.com/dedezinholindo/MC426/pull/27
- https://github.com/dedezinholindo/MC426/pull/28
- https://github.com/dedezinholindo/MC426/pull/37
- https://github.com/dedezinholindo/MC426/pull/48
- https://github.com/dedezinholindo/MC426/pull/56
- https://github.com/dedezinholindo/MC426/pull/70

Não foi necessário a criação do Figma nessa etapa.
