### ISSUE TITLE
História 4.1: Como usuário gostaria de receber notificações sobre atividades ou ocorrências.

### ISSUE THREAD

**Issue by ShiryuReb** [dedezinholindo/MC426#24]
Como usuário (membro da comunidade, preocupado com a segurança do bairro) gostaria que aplicativo receba notificações em tempo real sobre atividades ou ocorrências relevantes na minha área cadastrada (endereço fornecido no cadastro). As notificações têm o objetivo de manter o usuário informado e alerta sobre situações que possam necessitar de sua atenção, prevenindo possíveis problemas ou riscos à sua segurança.

Critérios de Aceite:

- As notificações devem ser entregues em tempo real.
- Ao tocar em uma notificação, o usuário é levado diretamente à tela inicial do aplicativo.
- As notificações devem conter informações simples e relevantes para rápida compreensão do usuário.

Figma: to be done

A funcionalidade de notificações deve ser acessível e eficaz, garantindo que os usuários estejam sempre cientes das ocorrências em sua região sem serem sobrecarregados com informações desnecessárias.

Esta história é parte do #22.

**Comment by IsabelaPSouza** [comment]
MRs para feature:

backend:

- Não foi necessário

frontend:

- https://github.com/dedezinholindo/MC426/pull/53
