### ISSUE TITLE
Validação de Denúncias

### ISSUE THREAD

**Issue by dedezinholindo** [dedezinholindo/MC426#3]
Validar a veracidade das denúncias por meio do feedback (upvote & downvote).

**Comment by oallace** [comment]
As denúncias (feitas em formato de postagem) podem ser validadas pelos usuários do aplicativo por meio de *likes* e *unlikes*.

Para tal fim implementar:
- [ ] *likes* em postagens
- [ ] *unlikes* em postagens
- [ ] Classificar post com base em seus *likes* e *unlikes*

**Comment by oallace** [comment]
### _Backend_

Versão do inicial do _backend_ da _feature_ implementada no _pull request_ #27.

#### Descrição 

Criação de uma API em Flask que permite:

- _Likes_ em postagens de denúncia;
- _Unlikes_ em postagens de denúncia;

#### Observações

Ainda é necessário implementar algumas funcionalidades:

- Incorporar informações de _login_ às denúncias;
  - Permitir um único _like/unlike_ por usuário em cada postagem.

Essas funcionalidades devem ser desenvolvidas em versões posteriores da _feature_.

**Comment by ShiryuReb** [comment]
### _Frontend_
Versão Inicial do Frontend para a Feature de Validação de Denúncias (Pull Request #43).

#### Descrição
A implementação desta feature no frontend em Flutter, explora a capacidade de interagir com as denúncias por meio de:

- Likes (upvotes/aprovação) em postagens de denúncias;
- Unlikes (downvotes/desaprovação) em postagens de denúncias.

#### Funcionalidades Implementadas

- Interação com Denúncias: Os usuários podem agora validar as denúncias expressando sua opinião através de likes e unlikes.
- Integração com o Backend: As ações de like e unlike são enviadas para a API do backend para atualizar o estado das postagens de denúncias.

#### Possíveis melhorias futuras

Algumas melhorias e funcionalidades adicionais estão planejadas para implementação futura, incluindo:

- Autenticação de Usuário: Vincular likes e unlikes a usuários autenticados, para garantir dados válidos e evitar flood.
- Limitação de Interações: Implementar lógica para permitir que um usuário dê apenas um like ou unlike por denúncia, mas permitindo que o mesmo possa alternar a qualquer momento entre um e outro.
