### ISSUE TITLE
Code Smell - Bloaters

### ISSUE THREAD

**Issue by IsabelaPSouza** [dedezinholindo/MC426#63]
Na classe main.dart o método main está muito grande e com muitas responsabilidades, deve ser quebrado em pelo menos 3 funções (setup providers, run e init firebase) 

<img width="769" alt="Captura de Tela 2023-12-13 às 00 01 35" src="https://github.com/dedezinholindo/MC426/assets/90933885/abb9cab4-01e8-4383-8582-1b0cab2b1797">

**Comment by ShiryuReb** [comment]
Corrigido no MR: https://github.com/dedezinholindo/MC426/pull/66
